# Big Data and Analytics V2 - EMC Certification

### R-Programming Language - Walkthrough the Certification

<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcT4r4wSr8WbLpsewIxDWGNXDyUDu5SzUUjrsGJgyRp9LzaCi0CL" width = "400px"></img>

##### On this Material you'll find:

<ul>
 <li>Some Basic Commands that will help you</li>
 <li>How to get Data in (Import) and out (Export) of R </li>
 <li>Data Types and Data Structures</li>
 <li>How to Access SQL with R </li>
</ul>

### Basic Commands that Helps:

In [ ]:
#help command: "?command" you need help
#example:
#?plot

In [4]:
#clean console
rm(list=ls())
dir()

[1] "02_02.ipynb"                                                                          
 [2] "02_04.ipynb"                                                                          
 [3] "03_02.ipynb"                                                                          
 [4] "03_03.ipynb"                                                                          
 [5] "04_05.ipynb"                                                                          
 [6] "05_07.ipynb"                                                                          
 [7] "05_11.ipynb"                                                                          
 [8] "1.1-Python-Basics-Functions.ipynb"                                                    
 [9] "1.3 - Python Basics - Working with Files - csv, xlsx, json - (Open, Write, etc).ipynb"
[10] "7-Dell_NLP_Cleaning Data, Stemming, Vectorizing, etc.ipynb"                           
[11] "AI_ENGINEERING_KERAS_FORECASTING.ipynb"                                               
[12] "Assignment Viz 2.ipynb"                                                               
[13] "Assignment+2.ipynb"                                                                   
[14] "Assignment+3.ipynb"                                                                   
[15] "Assignment+4.ipynb"                                                                   
[16] "Assignment3_Aviz.ipynb"                                                               
[17] "automl_binary_classification_product_backorders.ipynb"                                
[18] "AUTOML_h2o.ipynb"                                                                     
[19] "census.csv"                                                                           
[20] "citi_bike_small.ipynb"                                                                
[21] "Date_Work.ipynb"                                                                      
[22] "First_Studies-Copy1.ipynb"                                                            
[23] "First_Studies.ipynb"                                                                  
[24] "HTML_CSS_Basics.ipynb"                                                                
[25] "images"                                                                               
[26] "KERAS_COURSERA.ipynb"                                                                 
[27] "Michigan Python"                                                                      
[28] "ML_ASSIGNMENT_KNN_MICHIGAN PYTHON.ipynb"                                              
[29] "mtcars.csv"                                                                           
[30] "NLP"                                                                                  
[31] "olympics.csv"                                                                         
[32] "PCA and TRY OF REGRESSION.ipynb"                                                      
[33] "PCR_on_sensory_and_fluorescence_data.ipynb"                                           
[34] "phishing.csv"                                                                         
[35] "R Course Saba"                                                                        
[36] "R_EMC_Big_Data_Certification - Exploratory Analysis.ipynb"                            
[37] "R_EMC_Big_Data_Certification - Model Building and Evaluation.ipynb"                   
[38] "R_EMC_Big_Data_Certification - R Basics.ipynb"                                        
[39] "recommended_system_SVD_single_value_decomposition_algebra_method.ipynb"               
[40] "recommended_systems_classification_based_recom.ipynb"                                 
[41] "Recommended_Systems_Dell_Course.ipynb"                                                
[42] "sample.ipynb"                                                                         
[43] "simple_regression.ipynb"                                                              
[4

### Importing/Exporting Data with R

 <img src="images/R_EMC_Big_Data/R_Import.png" width="400" align="left">
  <img src="images/R_EMC_Big_Data/R_Export.png" width="400" align="right">

In [10]:
#get current directory
getwd()
#importing with read.csv
new_work_directory = "C:/Users/mateus_s_leao/Documents/Data Science and Programming/r-works"
setwd(new_work_directory)
data1 <- read.csv("challenger.csv", header=TRUE, sep=",")
#importing with read.delim
#data2 <- read.delim("", header=TRUE, sep=",")
#summary with statistical info
summary(data1)
#describe


   o_ring_ct  distress_ct      temperature       pressure       launch_id   
 Min.   :6   Min.   :0.0000   Min.   :53.00   Min.   : 50.0   Min.   : 1.0  
 1st Qu.:6   1st Qu.:0.0000   1st Qu.:67.00   1st Qu.: 75.0   1st Qu.: 6.5  
 Median :6   Median :0.0000   Median :70.00   Median :200.0   Median :12.0  
 Mean   :6   Mean   :0.3043   Mean   :69.57   Mean   :152.2   Mean   :12.0  
 3rd Qu.:6   3rd Qu.:0.5000   3rd Qu.:75.00   3rd Qu.:200.0   3rd Qu.:17.5  
 Max.   :6   Max.   :2.0000   Max.   :81.00   Max.   :200.0   Max.   :23.0  

ERROR: Error in describe(data1): no se pudo encontrar la función "describe"


### Get and Set the Working Directory:

In [25]:
default_work_directory = "C:/Users/mateus_s_leao/"
setwd(default_work_directory)
#to get the working directory:
wd = getwd()
#to set another working directory:
new_work_directory = "C:/Users/mateus_s_leao/Documents/Data Science and Programming/r-works"
setwd(new_work_directory)
#put the new work directory into a variable
nwd = getwd()

### Two-Ways to Print Text and Variables (Concatenated):

In [27]:
#1 - Print and Paste
print(paste0("Old working dir with print and paste: ", wd))
#2 - cat
cat("Current working dir with cat: ", nwd)

[1] "Old working dir with print and paste: C:/Users/mateus_s_leao"
Current working dir with cat:  C:/Users/mateus_s_leao/Documents/Data Science and Programming/r-works

### Data Types in R

<img src="images/R_EMC_Big_Data/Data_Types.png" width="150" align="left">

In [37]:
#Creating These Data Types
#had to convert the integer, otherwise it would be double/numeric
integer = as.integer(5)
numeric = 10.42
character_string = "my string is a phrase"
logic = FALSE
#Creating a Factor: starts with a list
directions <- c("North", "East", "East", "South", "South", "South")
dir_factor = factor(directions, levels= c("North", "East", "South", "West"), labels=c("N", "E", "S", "W"))
cat("my integer is: ", integer, "and the type of it is: ", typeof(integer),
    "\nmy numeric is: ", numeric, "and the type of it is: ", typeof(numeric),
    "\nmy string/character is: ", character_string, "and the type of it is: ", typeof(character_string),
    "\nmy logical value is: ", logic, "and the type of it is: ", typeof(logic),
    "\nand my factor values are: ",dir_factor, "\n\n")
print("printing my factor with 4 levels:")
dir_factor


my integer is:  5 and the type of it is:  integer 
my numeric is:  10.42 and the type of it is:  double 
my string/character is:  my string is a phrase and the type of it is:  character 
my logical value is:  FALSE and the type of it is:  logical 
and my factor values are:  1 2 2 3 3 3 

[1] "printing my factor with 4 levels:"


[1] N E E S S S
Levels: N E S W

### Data Attributes

<img src="images/R_EMC_Big_Data/Data_Attributes.png" width="600" align="left">

### Data Structures in R

<img src="images/R_EMC_Big_Data/Data_Structure.PNG" width="450" align="right">
<ul> 
    <li>Atomic Vectors</li>
        <ul>
            <li>Just Referred as Vectors</li>
            <li>Indexed Sequence of <b>Same Data Type Items</b></li>
        </ul>
</ul>

<ul> 
    <li>Lists</li>
        <ul>
            <li>Special Type of Vector</li>
            <li>Contains Indexed Sequence of Objects of <b>Different Types </b></li>
        </ul>
</ul>

<ul> 
    <li>Arrays</li>
        <ul>
            <li><b>N-Dimensional</b></li>
            <li>Indexed Sequenced of values of <b>Same Data Type</b></li>
        </ul>
</ul>

<ul><li><i>To see type of structures use "Class()"</i></li></ul>

#### Vector:

In [76]:
#creating some Structures in R
#start with Vectors
vector_1 <- c(1,2,3,5)
#accessing members of vector with indexer
vector_1[3]
#confirming the type
is.atomic(vector_1)
is.vector(vector_1)


[1] 3

[1] TRUE

[1] TRUE

#### List:

In [77]:
#creating a list
list_1 = list(1,"Mark",523.23,TRUE, vector_1)
#list displays the multiple vector values (vector_1 above) in just one line
list_1
cat("getting the 4th element of the 5th element of the list: ",list_1[[5]][[4]],"\n\n")




[[1]]
[1] 1

[[2]]
[1] "Mark"

[[3]]
[1] 523.23

[[4]]
[1] TRUE

[[5]]
[1] 1 2 3 5

getting the 4th element of the 5th element of the list:  5 



#### Array (3 Dimensions, 3rd being page)

In [110]:
#Arrays (N-Dimensional)
#build a 3 dimensional array
#with rows = 3, col = 4, and pages = 2
array_1 <- array(1, dim=c(3,4,2))
#assign values to array
array_1[,,1] <- 5
array_1[1,1,1] <- 10
array_1[1,1,2] <- 10
array_1[,3,2] <- 6

print(array_1)
#see type of structure
class(array_1)

, , 1

     [,1] [,2] [,3] [,4]
[1,]   10    5    5    5
[2,]    5    5    5    5
[3,]    5    5    5    5

, , 2

     [,1] [,2] [,3] [,4]
[1,]   10    1    6    1
[2,]    1    1    6    1
[3,]    1    1    6    1



[1] "array"

#### Matrix, Matrices:
<ul>
    <li>2-dim array</li>
    <li>1 Data Type only</li>
    <li>Transpose - t()</li>
    <li>Multiplication - %*%</li>
    <li>Determinant - det()</li>
</ul>

In [108]:
#demonstrating how to create a matrix with R
letter_mat <- matrix(c(1:26, 26:1, letters), nrow=26,ncol=3)
head(letter_mat,5)
#see type of structure
class(letter_mat)

[,1] [,2] [,3]
[1,] 1    26   a   
[2,] 2    25   b   
[3,] 3    24   c   
[4,] 4    23   d   
[5,] 5    22   e

[1] "matrix"

#### Data Frames (Tables)
<ul>
    <li>2-dim data structure</li>
    <li>Columns can be easily referenced by name</li>
    <li>Different Columns may have different Data Types</li>
    <li><b>By Default, data.frame() treats character data as factor</b></li>
</ul>

In [111]:
seq <- c(1:26)
letter_df <- data.frame(seq, letters, stringsAsFactors=FALSE)
head(letter_df)
#see type of structure
print("my type of structure is :", class(letter_df)

seq letters
1 1   a      
2 2   b      
3 3   c      
4 4   d      
5 5   e      
6 6   f

[1] "data.frame"

#### Factors
<ul>
    <li>A factor is a variable with specific levels (categories)</li>
    <li>Useful to Analyze Categorical Data</li>
    <li>Two Types of Factors:</li>
        <ul>
            <li>Unordered for Nominal Data: Cat, Dog, Monkey</li>
            <li>Ordered for Ordinal Data: Gold, Silver, Bronze</li>
        </ul>
</ul>

### Access SQL Database with R

In [ ]:
#Add RODBC Package
#install.packages("RODBC")
#library(RODBC)
#Establish ODBC Connection
#conn <- odbcConnect("mydb",
#                   uid="user",
#                   pwd="password")
#Import Data from Query
#query <- sqlQuery(conn, "select * from table")